apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-componentstatuses-exporter
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: k8s-componentstatuses-exporter
rules:
- apiGroups:
  - ""
  resources:
  - componentstatuses
  verbs:
  - list

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-componentstatuses-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-componentstatuses-exporter
subjects:
- kind: ServiceAccount
  name: k8s-componentstatuses-exporter
  namespace: kube-system
