apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-componentstatuses-prometheus-exporter.fullname" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: {{ template "kube-componentstatuses-prometheus-exporter.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - componentstatuses
  verbs:
  - list

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kube-componentstatuses-prometheus-exporter.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kube-componentstatuses-prometheus-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kube-componentstatuses-prometheus-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
