{{- if .Values.ServiceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "componentstatuses-exporter.name" . }}
    chart: {{ template "componentstatuses-exporter.chart" . }}
    prometheus: {{ .Values.ServiceMonitor.prometheus }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  endpoints:
  - interval: {{ default "30s" .Values.ServiceMonitor.interval }}
    port: {{ default "http" .Values.ServiceMonitor.port }}
  jobLabel: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "componentstatuses-exporter.name" . }}
      release: {{ .Release.Name }}
{{- end }}
